'use strict';

let data,view='single',year=2025,entity='3400',metric='budget',selectedYears=[2021,2022,2023,2024,2025],rows=[],current,selected=null;
const $=id=>document.getElementById(id),colors={position:'#234a66',adjust:'#9aabb8',price:'#bb852f',transfer:'#7965a8',increase:'#21847b',decrease:'#b8626a',obligation:'#287cad',rounding:'#9aabb8'};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const amount=(n,sign=false)=>n==null?'Not available':(sign&&n>0?'+':'')+(n/Number($('units').value)).toLocaleString('en-US',{minimumFractionDigits:1,maximumFractionDigits:1});
const unit=()=>Number($('units').value)===1000?'$M':'$K';
const sourceLink=(r,label)=>`<a href="${r.source}#page=${r.page}" target="_blank" rel="noopener">${esc(label)}</a>`;
function yearControls(){document.querySelector('.filters')?.classList.toggle('trend-filters',view==='trend');if(view==='bridge'&&year<2022)year=2022;let html='';if(view==='bridge')html=`<label>Compare fiscal years<select id="year">${[2022,2023,2024,2025,2026,2027].map(y=>`<option value="${y}" ${year===y?'selected':''}>FY${y-1} → FY${y}</option>`).join('')}</select></label>`;else if(view==='single')html=`<label>Fiscal year<select id="year">${[2021,2022,2023,2024,2025,2026,2027].map(y=>`<option ${year===y?'selected':''}>${y}</option>`).join('')}</select></label>`;else html=`<label class="measure-filter">Funding measure<select id="metric"><option value="budget">Budget</option><option value="obligations">Obligations</option><option value="congress">Congressional Action</option><option value="adjustments">Reprogramming / Adjustments</option></select></label><fieldset class="fiscal-years"><legend>Fiscal years</legend><div class="yearchecks">${[2021,2022,2023,2024,2025,2026,2027].map(y=>`<label><input type="checkbox" value="${y}" ${selectedYears.includes(y)?'checked':''}>${y}</label>`).join('')}</div></fieldset>`;$('year-controls').innerHTML=html;if($('year'))$('year').onchange=e=>{year=+e.target.value;render()};if($('metric')){$('metric').value=metric;$('metric').onchange=e=>{metric=e.target.value;render()};document.querySelectorAll('.yearchecks input').forEach(c=>c.onchange=()=>{selectedYears=[...document.querySelectorAll('.yearchecks input:checked')].map(x=>+x.value);render()})}}
function makeRow(label,value,type='position',delta=false){return {label,value,type,delta}}
function render(){syncBudgetLevels();$('category-help').hidden=false;$('category-help').setAttribute('aria-label',view==='trend'?'About Funding Over Time':view==='bridge'?'About the J-book comparison':'Information about the six budget categories');$('category-help').title=view==='trend'?'About Funding Over Time':view==='bridge'?'About the J-book comparison':'The six budget categories';if(view!=='single'&&$('categories').open)$('categories').close();$('show-overview').hidden=true;selected=null;current=null;rows=[];$('drivers').innerHTML='';$('notice').hidden=true;$('selection').textContent='Select a bar to update Behind the Numbers below.';$('unit-tag').textContent=metric==='rate'&&view==='trend'?'Percent':unit();$('legend').innerHTML='';$('stats').innerHTML='';$('references').innerHTML='';$('table-note').textContent='Amounts are rounded for display. Calculations use source precision.';let title,subtitle,kicker,explanation;
if(view==='bridge'){
 const b=data.bridges[`${year}-${entity}`];if(!b){$('view-kicker').textContent='YEAR-TO-YEAR COMPARISON';$('chart-title').textContent=`FY${year-1} to FY${year} · ${data.entities[entity]}`;$('chart-subtitle').textContent='';$('narrative-title').textContent='Source coverage';$('narrative').innerHTML='<p>No verified J-book comparison is available for this selection. FY2021’s base-only J-book is available in Source documents; its base figures are not substituted for combined base + OCO funding. Choose Funding Over Time for available execution positions.</p>';drawChart();renderInsights();return;}current=b;if(b.summaryOnly){renderParentBridge(b);renderInsights();return;}kicker='YEAR-TO-YEAR COMPARISON';title=`FY${year-1} to FY${year} · ${data.entities[entity]}`;subtitle='The comparison with the strongest documented explanations for change.';
 rows=[makeRow(year===2025?'FY2024 estimate':`FY${year-1} appropriated`,b.start)];
 if(b.adjustments)rows.push(makeRow('Baseline adjustments',b.adjustments,'adjust',true));rows.push(makeRow('Price changes',b.price,'price',true),makeRow('Transfers',b.transfers,'transfer',true));
 if(b.increases!=null)rows.push(makeRow('Program increases',b.increases,'increase',true),makeRow('Program decreases',b.decreases,'decrease',true));else rows.push(makeRow('Net program changes',b.program,b.program<0?'decrease':'increase',true));rows.push(makeRow(`FY${year} request`,b.request));
 $('stats').innerHTML=stat('Starting position',b.start)+stat('New request',b.request)+stat('Change from starting position',b.request-b.start,true);
 $('legend').innerHTML=Object.entries({position:'Funding position',price:'Price',transfer:'Transfers',increase:'Program increases',decrease:'Program decreases'}).map(([k,v])=>`<span><i class="swatch" style="background:${colors[k]}"></i>${v}</span>`).join('');
 explanation=`The FY${year} request is ${amount(b.request-b.baseline,true)} ${unit()} relative to the J-book’s normalized prior-year baseline. Price changes contribute ${amount(b.price,true)} ${unit()}, transfers ${amount(b.transfers,true)} ${unit()}, and net program changes ${amount(b.program,true)} ${unit()}.`;
 if(b.increases!=null)explanation+=` Program increases of ${amount(b.increases)} ${unit()} and decreases of ${amount(b.decreases)} ${unit()} are shown separately so the net change does not hide the larger movements.`;
 if(b.adjustments)explanation+=` Before those changes, the book moves from its appropriated position to a normalized baseline of ${amount(b.baseline)} ${unit()}. Baseline adjustments are calculated from those two reported positions; their specific components are in the reconciliation.`;
 if(year===2022){notice('FY2021 includes base + OCO in this later J-book baseline. FY2022 incorporates former OCO costs into base; transfers and scope changes should be considered.');}
 if(year===2025){notice('FY2024 is an estimate in the FY2025 J-book, prepared before full-year enactment. This view preserves that book’s historical baseline; it does not substitute the later FY2024 DD 1414.');explanation+=' The source’s FY2024 starting position is an estimate, even where the exhibit uses an “appropriated” row label.'}
 if(year===2026&&entity==='021A'){notice('Source snapshot matters: this J-book shows FY2025 appropriated funding of 3,498.8 $M, then adds 350.0 $M of fact-of-life changes and 3.3 $M of supplemental funding. The year-end report classifies the 350.0 $M in enacted funding.');}
 if(year>=2026)$('table-note').textContent+=' Discretionary OP-5 bridge only; separately reported mandatory funding is excluded.';
 $('drivers').innerHTML=b.drivers.slice(0,4).map(d=>`<div class="driver ${d.amount<0?'negative':''}"><span class="amount">${amount(d.amount,true)} ${unit()}</span><strong>${esc(d.title)}</strong><p>${esc(d.description)}</p></div>`).join('');
 $('references').innerHTML=`<p>${sourceLink(b,`FY${year} J-book · OP-5, ${entity} · printed p. ${b.printed} / PDF p. ${b.page}`)}</p><p>Reconciliation Summary and subsequent Reconciliation of Increases and Decreases. Narrative excerpts retain source wording. Program decreases may include removal of temporary funding; a negative amount does not, by itself, establish a recurring program cut.</p>`;
}else if(view==='single'){
 const e=data.execution[`${year}-${entity}`];current=e;kicker='ONE YEAR’S BUDGET';title=`FY${year} · ${data.entities[entity]}`;subtitle='From the original request through year-end obligations.';
 if(e){rows=[makeRow('Budget Request',e.request),makeRow('Congressional Action',e.congress,'adjust',true),makeRow('Enacted',e.enacted),makeRow('Reprogramming / Adjustments',e.adjustments,'transfer',true),makeRow('Updated Budget',e.updated),makeRow('Obligations',e.obligations,'obligation')];$('stats').innerHTML=stat('Updated budget',e.updated)+stat('Obligations',e.obligations)+rateStat(e);explanation=`As of ${e.asof}, obligations were ${amount(e.obligations)} ${unit()} against an updated budget of ${amount(e.updated)} ${unit()}. Obligations represent commitments of budget authority, not cash payments.`;
 $('references').innerHTML=`<p>${sourceLink(e,`FY${year} year-end execution report · ${entity} · PDF p. ${e.page}`)}</p><p>${accountLabel()}. Annual appropriation 3400 only. Report labels “Net” and “Enacted Appropriation” map to Updated Budget and Enacted.</p>`;$('table-note').textContent='Congressional Action and Reprogramming / Adjustments are calculated net changes between reported funding positions; they do not identify individual actions.';
 if(e.updated==null){explanation=`The supplied ${e.sourceKind} establishes a request of ${amount(e.request)} ${unit()} ${e.enacted==null?'for this area; enacted funding is not established in this snapshot':`and enacted funding of ${amount(e.enacted)} ${unit()} for this area`}. Updated Budget and Obligations are not established by this source.`;$('chart-subtitle').textContent=`Available funding positions · ${e.sourceKind}`;$('references').innerHTML=`<p>${sourceLink(e,`FY${e.sourceYear||year} ${e.sourceKind} · ${entity} · PDF p. ${e.page}`)}</p>`;}
 if(year===2021)explanation+=' FY2021 annual funding includes base + OCO.';
 if(Math.abs(e.adjustments-e.reportedAdjustments)>.001){notice('Source discrepancy: the report’s listed adjustment components do not reconcile to its reported Net for this row. Values are preserved, and the graph uses the calculated net change.');explanation+=` Listed adjustments total ${amount(e.reportedAdjustments)} ${unit()}, whereas Updated Budget minus Enacted is ${amount(e.adjustments)} ${unit()}. The difference is not explained by this report.`;}
 }else{explanation='Year-end execution is not loaded for this selection. No zero or estimated obligations have been substituted.';notice('No matched execution row is available for this fiscal year, budget area, within annual appropriation 3400.');}
}else{
 kicker='FUNDING OVER TIME';const names={budget:'Budget',obligations:'Obligations',congress:'Congressional Action',adjustments:'Reprogramming / Adjustments'};
 title=`${names[metric]} · ${data.entities[entity]}`;
 subtitle='';
 const series=metric==='budget'?[['request','Budget Request','#234a66'],['enacted','Enacted','#428bb4'],['updated','Updated Budget','#21847b']]:[[metric,names[metric],metric==='congress'?'#ad711d':metric==='adjustments'?'#7965a8':'#287cad']];
 rows=selectedYears.flatMap(y=>series.map(([key,stage,color])=>{const e=data.execution[`${y}-${entity}`],b=data.bridges[`${y}-${entity}`];const ref=e||(key==='request'?b:null);return {...makeRow(`FY${y} · ${stage}`,e?.[key]??(key==='request'?b?.request:null)??null),year:y,stage,key,color,ref,refKind:e?'execution':'request',signed:['congress','adjustments'].includes(key)}}));
 $('legend').innerHTML=series.map(([k,label,color])=>`<span><i class="swatch" style="background:${color}"></i>${label}</span>`).join('');
 explanation=metric==='budget'?'Each fiscal year has three separate funding positions: Budget Request, Enacted, and Updated Budget. The gap between Request and Enacted is Congressional Action; the gap between Enacted and Updated Budget is Reprogramming / Adjustments. Select a bar to see how that position was built.':metric==='congress'?'Each bar shows the net change from that fiscal year’s request to enacted funding. Positive bars are net additions; negative bars are net reductions. Select a bar for the documented components and any differences in how the sources classify them.':metric==='adjustments'?'Each bar shows the net change from enacted funding to the updated budget in that year’s September 30 report. Select a bar for the reported adjustment types and any unresolved reconciliation differences.':'Each bar shows September 30 obligations for annual appropriation 3400. Select a bar for its funding context and obligation rate. Obligations were commitments of budget authority, not cash payments.';
 if(rows.some(r=>r.value==null))notice('Some selected figures are unavailable. See the information button for coverage.');
 if(metric==='budget'&&selectedYears.some(y=>y>=2026))explanation+=' FY2026–2027 request bars use the discretionary OP-5 bridge; separately reported mandatory funding is excluded.';
 const refs=[...new Map(rows.filter(r=>r.ref).map(r=>[r.year+'-'+r.ref.source,r])).values()];
 $('references').innerHTML=refs.map(r=>`<p>${sourceLink(r.ref,`FY${r.ref.sourceYear||r.year} ${r.ref.sourceKind|| (r.refKind==='execution'?'year-end execution':'J-book · OP-5')} · ${entity} · PDF p. ${r.ref.page}`)}</p>`).join('');
 $('table-note').textContent=metric==='budget'?'Execution positions use matching annual-account reports; request-only or enacted snapshots identify their separate source. FY2021 annual funding includes base + OCO; FY2022 incorporates former OCO costs into base.':'Net changes use matching positions in the same report; they do not by themselves identify individual actions or causes.';

}
$('view-kicker').textContent=kicker;$('chart-title').textContent=title;$('chart-subtitle').textContent=subtitle;$('narrative-title').textContent=view==='bridge'?'What changed, and why':view==='single'?'Reading the funding picture':'Reading the trend';$('narrative').innerHTML=`<p>${esc(explanation)}</p>`;drawChart();renderInsights();}
function notice(t){$('notice').hidden=false;$('notice').textContent=t}
function stat(label,n,sign=false){return `<div class="stat"><small>${label}</small><strong>${amount(n,sign)} <span style="font-size:13px;font-weight:400">${unit()}</span></strong></div>`}
function drawChart(){if(view==='trend'){drawTrend();return;}if(!rows.length){$('chart').innerHTML='<div class="empty">No verified observations for this selection.<br>Choose an available year or measure.</div>';return}let running=0;const bars=rows.map(r=>{let from=0,to=r.value??0;if(r.delta){from=running;to=running+r.value;running=to}else if(view!=='trend'){running=to}return {...r,from,to}});let max=Math.max(...bars.map(b=>Math.max(b.from,b.to)),1)*1.17,min=Math.min(0,...bars.map(b=>Math.min(b.from,b.to)));const width=Math.max(820,$('chart').clientWidth||820),height=Math.max(160,Math.min(320,$('chart').clientHeight||280)),left=65,right=15,top=22,bottom=66,plotH=height-top-bottom;const y=v=>top+(max-v)/(max-min)*plotH,step=(width-left-right)/bars.length,bw=Math.min(63,step*.56);let svg=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc($('chart-title').textContent)}"><title>${esc($('chart-title').textContent)}</title>`;for(let i=0;i<5;i++){let v=min+(max-min)*i/4;svg+=`<line x1="${left}" x2="${width-right}" y1="${y(v)}" y2="${y(v)}" stroke="#e8eef2"/><text x="${left-9}" y="${y(v)+4}" fill="#758796" text-anchor="end" font-size="11">${view==='trend'&&metric==='rate'?v.toFixed(0)+'%':amount(v)}</text>`}
bars.forEach((b,i)=>{let x=left+step*i+step/2,yt=y(Math.max(b.to,b.from)),h=Math.max(Math.abs(y(b.to)-y(b.from)),b.value===0?2:4);let label=b.label.split(' ');svg+=`<g>`;if(b.value!=null){svg+=`<rect data-index="${i}" tabindex="0" role="button" aria-label="${esc(b.label)}: ${esc(amount(b.value,b.delta))}" x="${x-bw/2}" y="${yt}" width="${bw}" height="${h}" rx="2" fill="${colors[b.type]}"><title>${esc(b.label)}: ${view==='trend'&&metric==='rate'?b.value.toFixed(1)+'%':amount(b.value,b.delta)+' '+unit()}</title></rect><text x="${x}" y="${yt-8}" text-anchor="middle" fill="#29495e" font-size="11" font-weight="600">${view==='trend'&&metric==='rate'?b.value.toFixed(1)+'%':amount(b.value,b.delta)}</text>`;}else svg+=`<text x="${x}" y="${y(0)-10}" text-anchor="middle" fill="#7b8c99" font-size="12">No data</text>`;let parts=label.length>2?[label.slice(0,2).join(' '),label.slice(2).join(' ')]:label;parts.forEach((t,k)=>svg+=`<text x="${x}" y="${height-bottom+22+k*14}" text-anchor="middle" fill="#63798a" font-size="11">${esc(t)}</text>`);svg+='</g>'});svg+='</svg>';$('chart').innerHTML=svg;document.querySelectorAll('#chart rect[data-index]').forEach(r=>{const select=()=>{selected=rows[+r.dataset.index];$('selection').textContent=`${selected.label}: ${view==='trend'&&metric==='rate'?selected.value.toFixed(1)+'%':amount(selected.value,selected.delta)+' '+unit()}.`;explainFigure();document.querySelectorAll('#chart rect[data-index]').forEach(bar=>{bar.classList.toggle('selected-bar',bar===r);bar.setAttribute('aria-pressed',bar===r?'true':'false')});};r.onclick=select;r.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();select()}}})}
function drawTrend(){
 if(!rows.length){$('chart').innerHTML='<div class="empty">Select at least one fiscal year.</div>';return;}
 const grouped=metric==='budget',count=grouped?3:1,groupWidth=grouped?230:160,width=Math.max(820,$('chart').clientWidth||820,selectedYears.length*groupWidth+80),height=Math.max(160,Math.min(340,$('chart').clientHeight||280)),left=75,right=20,top=35,bottom=65,plotH=height-top-bottom;
 const values=rows.filter(r=>r.value!=null).map(r=>r.value),highest=Math.max(0,...values),lowest=Math.min(0,...values),range=Math.max(highest-lowest,1),max=highest+range*.16,min=lowest<0?lowest-range*.16:0;
 const y=v=>top+(max-v)/(max-min)*plotH,step=(width-left-right)/selectedYears.length,bw=grouped?Math.min(48,step*.2):Math.min(65,step*.5),gap=grouped?bw+9:0;
 let svg=`<svg style="min-width:${width}px" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc($('chart-title').textContent)}"><title>${esc($('chart-title').textContent)}</title>`;
 for(let i=0;i<5;i++){const value=min+(max-min)*i/4;svg+=`<line x1="${left}" x2="${width-right}" y1="${y(value)}" y2="${y(value)}" stroke="#e8eef2"/><text x="${left-10}" y="${y(value)+4}" text-anchor="end" fill="#758796" font-size="12">${amount(value)}</text>`;}
 svg+=`<line x1="${left}" x2="${width-right}" y1="${y(0)}" y2="${y(0)}" stroke="#8195a4"/>`;
 rows.forEach((r,i)=>{const group=Math.floor(i/count),index=i%count,x=left+step*(group+.5)+(index-(count-1)/2)*gap,barY=y(Math.max(0,r.value??0)),barH=Math.max(Math.abs(y(r.value??0)-y(0)),3),labelY=r.value<0?y(r.value)+18:barY-10;
 if(r.value!=null)svg+=`<rect data-index="${i}" tabindex="0" role="button" aria-pressed="false" aria-label="${esc(r.label)}: ${amount(r.value,r.signed)} ${unit()}" x="${x-bw/2}" y="${barY}" width="${bw}" height="${barH}" rx="2" fill="${r.color}"><title>${esc(r.label)}: ${amount(r.value,r.signed)} ${unit()}</title></rect><text x="${x}" y="${labelY}" text-anchor="middle" font-size="12" font-weight="600" fill="#29495e">${amount(r.value,r.signed)}</text>`;
 else svg+=`<text x="${x}" y="${y(0)-10}" text-anchor="middle" font-size="11" fill="#758796">N/A</text>`;
 if(index===0)svg+=`<text x="${left+step*(group+.5)}" y="${height-24}" text-anchor="middle" font-size="14" font-weight="600" fill="#456277">FY${r.year}</text>`;
 });svg+='</svg>';$('chart').innerHTML=svg;
 document.querySelectorAll('#chart rect[data-index]').forEach(bar=>{const select=()=>{selected=rows[+bar.dataset.index];$('selection').textContent=`${selected.label}: ${amount(selected.value,selected.signed)} ${unit()}.`;explainFigure();document.querySelectorAll('#chart rect[data-index]').forEach(b=>{b.classList.toggle('selected-bar',b===bar);b.setAttribute('aria-pressed',b===bar?'true':'false')});};bar.onclick=select;bar.onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();select()}}});
}
function explainFigure(){if(!selected)return;const region=document.querySelector('.narrative-scroll');if(region)region.scrollTop=0;renderInsights();}
$('show-overview').onclick=render;
$('category-help').onclick=()=>$(view==='trend'?'trend-guide':view==='bridge'?'comparison-guide':'categories').showModal();$('close-trend-guide').onclick=()=>$('trend-guide').close();$('close-comparison-guide').onclick=()=>$('comparison-guide').close();$('close-categories').onclick=()=>$('categories').close();
$('units').onchange=render;$('entity').onchange=e=>setBudgetLevel(e.target.value);document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;if(view==='single'&&![2021,2022,2023,2024,2025].includes(year))year=2025;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));yearControls();render()});$('about').onclick=()=>$('info').showModal();$('close-info').onclick=()=>$('info').close();$('download').onclick=()=>{let rate=view==='trend'&&metric==='rate';let csv='View,Scope,Account,Label,Amount,Units,Source basis\n'+rows.map(r=>[$('chart-title').textContent,entity,accountLabel(),r.label,r.value==null?'':rate?r.value:r.value/Number($('units').value),rate?'Percent':unit(),view==='bridge'?`FY${year} J-book ${current.exhibit||'OP-5'} PDF page ${current.page}`:view==='single'?`FY${year} ${accountLabel()} · ${current?.sourceKind||'September 30 execution'}`:'See dashboard references'].map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='budget-comparison.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
fetch('data.json').then(r=>{if(!r.ok)throw Error('Data unavailable');return r.json()}).then(d=>{data=d;$('entity').innerHTML=Object.entries(d.entities).map(([k,v])=>`<option value="${k}">${k} · ${v}</option>`).join('');$('entity').value=entity;setupCoverage();yearControls();render();initGuide()}).catch(()=>{$('guide-status').textContent='The budget data could not load. Please refresh the page.';$('chart').innerHTML='<p class="empty">The budget data could not load. Please refresh the page.</p>'});
